M48
; DRILL file {KiCad (6.0.0)} date Mon Oct 31 23:33:16 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-31T23:33:16+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
%
G90
G05
T1
X50.147Y-26.61
X50.147Y-32.39
T2
X46.0Y-17.2
X46.0Y-19.0
T0
M30
